### ISSUE TITLE
implement `!event next <event>`

### ISSUE THREAD

**Issue by vendethiel** [vendethiel/scalert#19]
if real fancy, should:
 - first exact match
 - then try "starts with"
 - then try contains

Should post about the 2 next events top.

Examples:

Bad: (shouln't include name to prevent injections/whatever)
```
user> !next BAD
bot> No upcoming event.
```
Exact match, one result:
```
user> !next Blizzcon: Qualifiers First Round
bot> Next Blizzcon: Qualifiers First Round in 1d 5h.
```
Exact match, two results:
```
user> !next GSL Code S
bot> Next GSL Code S in 1d 5, then 3d.
```
Inexact match, twice same:
```
user> !next GSL
bot> Next GSL Code S in 1d 5, then 3d.
```
Inexact match, different:
```
user> !next BTSL
bot> Next BSL: Europe in 1d 5, then BTSL: Asia in 1d 12h.
```

**Comment by Mudada** [comment]
What could be dope is that he pm you when the event is actually live

**Comment by vendethiel** [comment]
@Mudada see #15.
